tenstorrent/pytorch2.0_ttnn

.github/workflows/hello-world.yaml
PR to show working CI workflow and successful CI integration
Please rename the workflow when integration work begins.
Suggest to finish porting GH Orgs first
=> Add sample workflow to test ci vm runner

.github/pull_request_template.md
No ticket
Updating file to check merge queue
Minor tweak to pr template
=> Test of Merge Queue

.github/workflows/before_merge.yaml
No ticket
Keep experimenting with CI support in this repo.
This time tweaking when pipeline is triggered
=> Update Merge Queue Workflow

.github/pull_request_template.md
No ticket
Need to test workflow run
-
=> Setup workflow on default branch

.github/workflows/before_merge.yaml, .github/workflows/pull-request.yaml, requirements-dev.txt, requirements.txt
No ticket
We want to run tests before merging PRs
Added pytest run. This is not tested yet.
=> Add pytest run to the workflow

tools/generate_report.py, tools/run_torchvision.py, torch_ttnn/passes/stat_pass.py
None
Adding Black check on CI. But some files require formatting
Reformatting all files. 
Please refresh requirements and do `pre-commit install`
=> Run Black on all files

.github/workflows/before_merge.yaml
Link to Github Issue
Provide context for the problem
Describe the approach used to solve the problem.
Summarize the changes made and their impact
=> Enable Watcher to debug Bert hangs

requirements.txt
None
Updating ttnn
Checking for potential issues
=> Update ttnn to 0.5-rc25

README.md, tests/models/mnist/test_mnist.py
* test compiling and running mnist with training and eval
* updated README to include results from mnist
=> Add mnist test with train and inference

README.md, tools/collect_metrics.py, torch_ttnn/backend.py, torch_ttnn/utils.py
- Add links to the model name that points to the directory of the test
- Changed run success to use emojis
- Add unique torch op counts
- Change precision of numeric metrics to 2 decimal places
- Fix spacings
- Add a note about measuring multiple graphs
=> Polish metrics table in README

.gitignore, torch_ttnn/passes/lowering/to_tt_pass.py
- Minor fix in aten.t conversion pass
- Add data folder to .gitignore to avoid dump files during commit
=> Minor fix in aten.t conversion pass

torch_ttnn/metrics.py
None
Its too bad in dark schema
Update to a green one
=> Update success marker

README.md
Update README to include green checkmarks
=> Update README to include green checkmarks

README.md, docs/README.md.in, requirements-dev.txt, tests/models/bert/test_bert.py, tests/models/bloom/test_bloom.py, tests/models/falcon/test_falcon.py, tests/models/gpt2/test_gpt2.py, tests/models/llama/test_llama.py, tests/models/mnist/test_mnist.py, tests/models/resnet/test_resnet.py, tests/models/yolos/test_yolos.py, tools/collect_metrics.py, tools/data_collection/pydantic_models.py, torch_ttnn/backend.py, torch_ttnn/fx_graphviz.py, torch_ttnn/metrics.py
* Use Pydantic to organize the metrics and generate json files per model
* Write tables containing aten op information for each model
* Reorganize the collect metrics script
=> Generate metrics data with pydantic models

.github/workflows/pull-request.yaml, tests/conftest.py, tests/lowering/creation/test_clone.py, tests/lowering/eltwise/binary/test_eq.py, tests/lowering/embedding/test_embedding.py, tests/models/bert/test_bert.py, tests/models/bloom/test_bloom.py, tests/models/falcon/test_falcon.py, tests/models/gpt2/test_gpt2.py, tests/models/llama/test_llama.py, tests/models/mnist/test_mnist.py, tests/models/yolos/test_yolos.py, tests/tools/test_stats.py, tests/utils.py, tools/collect_metrics.py, tools/data_collection/pydantic_models.py, tools/generate_report.py, tools/run_torchvision.py, tools/run_transformers.py, tools/stat_models.py, tools/utils.py, torch_ttnn/backend.py, torch_ttnn/customized_replace/norm.py, torch_ttnn/fx_graphviz.py, torch_ttnn/handle_input_aliasing.py, torch_ttnn/metrics.py, torch_ttnn/passes/lowering/add_data_move_pass.py, torch_ttnn/passes/lowering/to_tt_pass.py, tracer/tracer.py
None
After bumping line width to 120, existing code might fail the format check.
Reformat the code with the new line width 120 using
```
pre-commit run --all-files
```
=> Reformat with latest pre-commit run --all-files

tests/models/deit/test_deit.py
None
Add model Deit to trace.
Add model Deit.
=> Model Deit

tests/models/distilbert/test_distilbert.py
None
Add model DistilBERT to trace.
Add model DistilBERT.
=> Model DistilBERT

tests/models/beit/test_beit_image_classification.py
None
Add model Beit to trace.
Add model Beit.
=> Model Beit

requirements-dev.txt, tests/models/clip/test_clip.py
Added a test for running model CLIP (image and text alignment) on torch_ttnn.
=> Add a test for model CLIP.

requirements-dev.txt, tests/models/mlpmixer/test_mlpmixer.py
None
Add model MLPMixer to trace.
Add model MLPMixer.
=> Model MLPMixer.

tests/models/detr/test_detr.py
None
Add model DETR to trace.
Add model DETR.
=> Model DETR.

tests/models/unet_brain/test_unet_brain.py
None
Add model Unet-brain to trace.
Add model Unet-brain.
=> Model Unet-brain.

tests/models/vilt/test_vilt.py
None
Add model ViLT to trace.
Add model ViLT.
=> Model ViLT.

tests/models/squeeze_bert/test_squeeze_bert.py
None
Add model SqueezeBERT to trace.
Add model SqueezeBERT.
=> Model SqueezeBERT.

tests/models/roberta/test_roberta.py
None
Add model RoBERTa to trace.
Add model RoBERTa.
=> Model RoBERTa

requirements-dev.txt, tests/models/timm/test_timm_image_classification.py
None
Add two more timm models: DLA, HRNet to trace.
Models added:
* DLA
* HRNet
=> Two more timm models: DLA, HRNet

tests/models/torchvision/test_torchvision_image_classification.py, tests/models/torchvision/test_torchvision_object_detection.py
None
Add torchvision models to trace.
Models to be added:
* Image Classification
* googlenet
* densenet
* mobilenet_v2
* mobilenet_v3
* resnet
* resnext
* vgg11
* vit
* wide_resnet
* regnet
* swin
* swin_v2
* Object Detection
* ssd
* ssdlite
* retinanet
=> Models from torchvision.

tests/models/unet/test_unet.py
None
Add model U-Net to trace.
Add model U-Net.
=> Model U-Net.

tests/measure_test_space_usage.py, tests/models/resnet50/test_resnet50.py, tests/models/torchvision/test_torchvision_image_classification.py, tests/models/torchvision/test_torchvision_object_detection.py
None
Locally got into an Out of Disk space situation.
Adding the script to capture disk space occupied by a model
=> Add a script measuring how much disk space each model takes

tests/models/codegen/test_codegen.py
None
Add model codegen to trace.
Add model codegen.
=> Model codegen

tests/models/flan_t5/test_flan_t5.py
None
Add model FLAN-T5 to trace.
Add model FLAN-T5.
=> Model FLAN-T5.

README.md, docs/cumulative_input_variations.md, docs/models/CLIP/input_variations.md, docs/models/DETR/input_variations.md, docs/models/DPR/input_variations.md, docs/models/FLAN-T5/input_variations.md, docs/models/Falcon/input_variations.md, docs/models/GLPN-KITTI/input_variations.md, docs/models/Llama/input_variations.md, docs/models/MLPMixer/input_variations.md, docs/models/ResNet50/input_variations.md, docs/models/RoBERTa/input_variations.md, docs/models/SegFormer/input_variations.md, docs/models/SqueezeBERT/input_variations.md, docs/models/Whisper/input_variations.md, docs/models/codegen/input_variations.md, docs/models/t5-base/input_variations.md, docs/models/t5-large/input_variations.md, docs/models/t5-small/input_variations.md, docs/models/twmkn9/albert-base-v2-squad2/input_variations.md, requirements-dev.txt, tests/conftest.py
None
We added lots of models and report is outdated
Running a data reporter
=> Update Model Data Report

tests/models/stable_diffusion/test_stable_diffusion.py
None
Add model Stable Diffusion to trace.
Add model Stable Diffusion.
=> Model Stable Diffusion.

tests/models/gpt_neo/test_gpt_neo.py
None
Add model GPT Neo to trace.
Add model GPT Neo.
=> Model GPT Neo.

tests/models/xglm/test_xglm.py
None
Add model XGLM to trace.
Add model XGLM.
=> Model XGLM.

tests/models/musicgen_small/test_musicgen_small.py
None
Add model musicgen-small to trace.
Add model musicgen-small.
=> Model musicgen-small.

tests/models/speecht5_tts/test_speecht5_tts.py
None
Add model speecht5_tts to trace.
Add model speecht5-tts.
=> Model speecht5-tts.

requirements-dev.txt, tests/models/openpose/test_openpose.py
None
Add model OpenPose to trace.
Add model OpenPose.
=> Model OpenPose.

tests/models/mobilenet_ssd/test_mobilenet_ssd.py
None
Add model MobileNetSSD to trace.
Add model MobileNetSSD.
=> Model MobileNetSSD.

tests/models/perceiver_io/test_perceiver_io.py
None
Add model Perceiver IO to trace.
Add model Perceiver IO.
=> Model Perceiver IO.

docs/ProblemSolving.md
None
Provide support for some common error messages 
* Add a section to cover errors hidden by Pytorch when a failure happens from the backend
* Add a section to cover incompatible function arguments
=> Add additional sections to ProblemSolving doc

torch_ttnn/CONTRIBUTING.md
None
We are recruiting developers to work on the compiler
A new document dedicated on writing op conversion
=> Create CONTRIBUTING.md on op conversion

tests/models/stable_diffusion/test_stable_diffusion.py, tests/models/stable_diffusion/test_stable_diffusion_v2.py
None
The original implementation has two issues:
1. Obsolete model link to Hugging Face.
2. Use as a pipeline.
We have fixed 1 but 2 is really a challenge to Dynamo, so we kept the original implementation as skipped for future study. We proposed another implementation of avoiding pipeline. 
Stable Diffusion now has two versions of implementations. One is with pipeline and the other not. The latter can work correctly.
=> Model Stable Diffusion, again

tests/models/hardnet/test_hardnet.py
None
Add model HardNet to trace.
Add model HardNet.
=> Model HardNet.

tests/models/autoencoder_linear/test_autoencoder_linear.py
None
Add model Autoencoder (linear) to trace.
Add model Autoencoder (linear).
=> Model Autoencoder (linear).

.github/workflows/UpdateTTNNWheel
None
Want to automate wheel update
This PR is a first step to automatically update TT-NN wheel
=> Create a workflow to automatically update TT-NN wheel

tests/lowering/pool/test_max_pool_2d.py, torch_ttnn/passes/lowering/add_data_move_pass.py, torch_ttnn/passes/lowering/to_tt_pass.py
None
Convert `aten.max_pool2d_with_indices` to `ttnn.max_pool2d`
=> Try converting `aten.max_pool2d_with_indices`

torch_ttnn/passes/lowering/to_tt_pass.py
None
Improve readability of `ReplaceMoreTtManually`
The list `new_nodes` was a local variable.  Its writing sides scattered hundreds of lines, but it was only read once.  I refactored generation of `new_nodes` to a function.  Writing `new_nodes` becomes returning a new node, which boosts readability.  We can also reuse the RAUW logic by simply returning a node.
=> Refactor manual lowering

requirements.txt
=> Update TT-NN to 0.52.0-rc20

.gitignore
None
.gitiignore generated .ttnn_runtime_artifacts
Ignore the generated directory
=> Ignore generated .ttnn_runtime_artifacts

.github/workflows/update-ttnn-wheel.yaml
Link to Github Issue
Provide context for the problem
Describe the approach used to solve the problem.
Summarize the changes made and their impact
=> Update update-ttnn-wheel workflow to be more stable

.github/workflows/update-ttnn-wheel.yaml
Enable automatic nightly ttnn wheel update
=> Update update-ttnn-wheel to support automerge

requirements.txt
=> Update TT-NN to 0.52.0-rc27

requirements.txt
=> Update TT-NN to 0.52.0-rc30

requirements.txt
=> Update TT-NN to 0.52.0-rc31

tests/conftest.py
n/a
Memory analysis pass is creating some issues with newly lowered OPs.
Will disable the pass for now, and re-enable later when we are done with push to bring up models.
Memory analysis pass disabled.
=> Disable memory analysis pass

tests/conftest.py, torch_ttnn/passes/lowering/to_tt_pass.py
n/a
Lower torch split to tt split for BERT model.
Added lowering on split to to_tt_pass
=> Add lowering of split to enable BERT

requirements.txt
=> Update TT-NN to 0.52.0-rc33

requirements.txt
=> Update TT-NN to 0.52.1-rc1

requirements.txt
=> Update TT-NN to 0.53.0-rc2

requirements.txt
=> Update TT-NN to 0.53.0-rc3

requirements.txt
=> Update TT-NN to 0.53.0-rc4

requirements.txt
=> Update TT-NN to 0.53.0-rc5

requirements.txt
=> Update TT-NN to 0.53.0-rc8

requirements.txt
=> Update TT-NN to 0.53.0-rc9

requirements.txt
=> Update TT-NN to 0.53.0-rc10

torch_ttnn/passes/lowering/to_tt_pass.py
Resolves tenstorrent/tt-metal#13420
We encountered real-world data that require this setting.
Enable `numeric_stable=True` for `ttnn.softmax`
=> Enable more numerical stability for `ttnn.softmax`

requirements.txt
=> Update TT-NN to 0.53.0-rc11

requirements.txt
=> Update TT-NN to 0.53.0-rc12

requirements.txt
=> Update TT-NN to 0.53.0-rc13

tools/generate_input_variation_test_from_models.py
N/A
Sorry I broke the main CI
Fix main CI pass
=> Fix CI failed at model-input-variations-tests

requirements.txt
=> Update TT-NN to 0.53.0-rc14

tests/models/autoencoder_conv/test_autoencoder_conv.py, tests/models/autoencoder_conv/test_autoencoder_conv_v2.py
None
None
Add training test of autoencoder conv
=> Training test autoencoder conv

tests/models/beit/test_beit_image_classification.py
None
None
Add training test of beit
=> Training test beit

tests/models/clip/test_clip.py
None
None
Add training test of autoencoder clip
=> Training test clip

tests/models/deit/test_deit.py
None
None
Add training test of autoencoder deit
=> Training test deit

tests/models/hardnet/test_hardnet.py
None
None
Add training test of hardnet
=> Training test hardnet

tests/models/openpose/test_openpose.py, tests/models/openpose/test_openpose_v2.py
None
None
Add training test of openpose
=> Training test openpose

tests/models/resnet/test_resnet.py, tests/models/resnet50/test_resnet50.py
None
None
Add training test of resnet
=> Training test resnet

tests/models/segformer/test_segformer.py
None
None
Add training test of segformer
=> Training test segformer

tests/models/timm/test_timm_image_classification.py
None
None
Add training test of timm
=> Training test timm

tests/models/unet/test_unet.py
None
None
Add training test of unet
=> Training test unet

tests/models/unet_brain/test_unet_brain.py
None
None
Add training test of unet_brain
=> Training test unet brain

requirements.txt
=> Update TT-NN to 0.53.0-rc16

tests/tools/test_input_vals_utils.py, tests/utils.py, tools/aten_test.tmpl
#316 
Need an unittest to test utils function's functionality
- Rename `get_input_vals_from_metric_str` as `render_metric_string_list_to_input_args_kwargs`
- Refactor `render_metric_string_list_to_input_args_kwargs`
- Add unittest of `render_metric_string_list_to_input_args_kwargs`
=> Add unit test of input variation utils function

.github/workflows/before_merge.yaml, tests/models/hardnet/test_hardnet.py
None
Onboard new runners to CI
We now run on both n300 and n150
Because runners are not uniform now, I am worried that numbers will fluctuate
=> Run CI on all in-service runners (both n150 and n300)

requirements.txt
=> Update TT-NN to 0.53.0-rc25

requirements.txt
=> Update TT-NN to 0.53.0-rc27

.github/workflows/before_merge.yaml
N/A
tmp change of before_merge.yaml accidentally merged in master
- Revert before_merge.yaml
- Add git pull in collect-meterics and push-autogen-op-tests
=> Revert before merge

tests/utils.py
#375 
See #375 
Fixed seed in `test_model_eval`
Although there is a chance to fail, but I ran and pass three times in CI, so I think maybe I fixed it
=> Fixed seed in `test_model_eval`

requirements.txt
=> Update TT-NN to 0.53.0-rc35

requirements.txt
=> Update TT-NN to 0.53.0-rc36

requirements.txt
=> Update TT-NN to 0.53.0-rc37

requirements.txt
=> Update TT-NN to 0.53.0-rc38

tests/lowering/eltwise/unary/test_hardtanh.py, torch_ttnn/passes/lowering/to_tt_pass.py
N/A
N/A
Replace aten.hardtanh with ttnn.hardtanh, I ran `pytest tests/autogen_op/ALL/test_ALL_aten_hardtanh_default.py --input_var_check_accu` pass
=> Replace aten.hardtanh with ttnn.hardtanh

requirements.txt
=> Update TT-NN to 0.53.0-rc39

requirements.txt
=> Update TT-NN to 0.53.0-rc41

tests/lowering/eltwise/unary/test_elu.py, torch_ttnn/passes/lowering/add_data_move_pass.py, torch_ttnn/passes/lowering/to_tt_pass.py
N/A
Add conversion from `aten.elu` to `ttnn.elu`
- Add conversion from `aten.elu` to `ttnn.elu`
- Add unit tests
All model tests are running: https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/11907360749
=> Convert `aten.elu` to `ttnn.elu`

requirements.txt
=> Update TT-NN to 0.53.0-rc47

requirements.txt
=> Update TT-NN to 0.53.0-rc50

requirements.txt
=> Update TT-NN to 0.53.1-rc1

requirements.txt
=> Update TT-NN to 0.53.1-rc2

requirements.txt
=> Update TT-NN to 0.53.1-rc8

requirements.txt
=> Update TT-NN to 0.53.1-rc9

requirements.txt
=> Update TT-NN to 0.53.1-rc11

requirements.txt
=> Update TT-NN to 0.53.1-rc13

requirements.txt
=> Update TT-NN to 0.53.1-rc14

requirements.txt
=> Update TT-NN to 0.53.1-rc15

tests/lowering/eltwise/unary/test_log.py, torch_ttnn/passes/lowering/to_tt_guard_autogen.py
#590 
N/A
- Remove blocklist of `aten.log.default`
=> Remove blocklist of `aten.log.default`

.github/workflows/update-ttnn-wheel.yaml, requirements.txt, torch_ttnn/passes/lowering/target_wrappers.py, torch_ttnn/passes/lowering/to_tt_pass.py
=> Update TT-NN to 0.53.1-rc22

requirements.txt
=> Update TT-NN to 0.53.1-rc23

requirements.txt
=> Update TT-NN to 0.53.1-rc25

tests/lowering/tensor_manipulation/test_constant_pad_nd.py, torch_ttnn/passes/lowering/to_tt_pass.py
https://github.com/tenstorrent/tt-metal/issues/15602
Support front padding of `aten.constant_pad_nd.default`
Support front padding of `aten.constant_pad_nd.default`
=> Support front padding

requirements.txt
=> Update TT-NN to 0.54.0-rc1

tests/lowering/eltwise/unary/test_aten_log_softmax.py, torch_ttnn/passes/lowering/to_tt_pass.py, torch_ttnn/utils.py
#640 
N/A
- Implement lowering of `aten._log_softmax.default`
=> Implement lowering of `aten._log_softmax.default`

tests/lowering/eltwise/binary/test_pow_scalar.py, tests/lowering/eltwise/binary/test_pow_tensor_scalar.py, tests/lowering/eltwise/binary/test_pow_tensor_tensor.py, tests/lowering/eltwise/unary/test_square.py, torch_ttnn/passes/lowering/to_tt_pass.py, torch_ttnn/utils.py
#643
N/A
- Implement lowering of `aten.pow.Scalar` and `aten.pow.Tensor_Tensor`
=> Implement lowering of `aten.pow.Scalar` and `aten.pow.Tensor_Tensor`

tests/conftest.py, tests/models/glpn_kitti/test_glpn_kitti.py, tests/models/mobilenet_ssd/test_mobilenet_ssd.py, tests/models/torchvision/test_torchvision_object_detection.py, tests/utils.py, torch_ttnn/passes/lowering/to_tt_guard.py
N/A
Now some blocklist is pass, and some model test is pass, so update it
- update to_tt_guard.py
- remove compilation_xfail of `GLPN-KITTI`, `MobileNetSSD `, `ssd300_vgg16 `, `ssdlite320_mobilenet_v3_large `
=> Update guard function

tests/lowering/eltwise/binary/test_lt.py
- Resolves #591
Not sure which cases to work on.  Is there a list of failing cases?
- Test cases listed in [`docs/operations/aten.lt.Scalar.md`](https://github.com/tenstorrent/pytorch2.0_ttnn/tree/main/docs/operations/aten.lt.Scalar.md)
=> Add test cases for conversion from `aten.lt.Scalar` to `ttnn.lt`

requirements.txt
=> Update TT-NN to 0.54.0-rc6

torch_ttnn/passes/lowering/to_tt_guard.py, torch_ttnn/passes/lowering/to_tt_guard_autogen.py, torch_ttnn/passes/lowering/to_tt_pass.py
N/A
Clean autogen guard function
- Remove blocklist of 
```
maximum.default
_log_softmax.default
div.Tensor
exp.default
where.self
empty.memory_format
rsqrt.default
bernoulli.p
native_dropout.default
new_empty_strided.default
mm.default
```
- add check in to_tt_pass
=> Clean `to_tt_guard_autogen`

.github/workflows/before_merge.yaml
N/A
N/A
- Update autogen_op tests - not sure why it change, but seems it's better like some `s0/s1` gone
- Add abck `Stable_Diffusion_V2/test_Stable_Diffusion_V2_aten_convolution_default.py`
- Not remove `test_Stable_Diffusion_V2_aten_convolution_default.py` in CI
=> Update autogen_op tests

requirements.txt
=> Update TT-NN to 0.54.0-rc7

requirements.txt
=> Update TT-NN to 0.54.0-rc8

requirements.txt
=> Update TT-NN to 0.54.0-rc9

requirements.txt
=> Update TT-NN to 0.54.0-rc10

requirements.txt
=> Update TT-NN to 0.54.0-rc11

requirements.txt
=> Update TT-NN to 0.54.0-rc13

requirements.txt
=> Update TT-NN to 0.54.0-rc16

requirements.txt
=> Update TT-NN to 0.54.0-rc17

requirements.txt
=> Update TT-NN to 0.54.0-rc18

requirements.txt
=> Update TT-NN to 0.54.0-rc19

requirements.txt
=> Update TT-NN to 0.54.0-rc23

requirements.txt
=> Update TT-NN to 0.55.0-rc10

requirements.txt
=> Update TT-NN to 0.55.0-rc18

requirements.txt
=> Update TT-NN to 0.55.0-rc19

requirements.txt
=> Update TT-NN to 0.55.0-rc20

requirements.txt
=> Update TT-NN to 0.56.0-rc1

requirements.txt
=> Update TT-NN to 0.56.0-rc2

requirements.txt
=> Update TT-NN to 0.56.0-rc3

requirements.txt
=> Update TT-NN to 0.56.0-rc7

requirements.txt
=> Update TT-NN to 0.56.0-rc9

requirements.txt
=> Update TT-NN to 0.56.0-rc43

requirements.txt
=> Update TT-NN to 0.56.1-rc1

requirements.txt
=> Update TT-NN to 0.56.1-rc3

requirements.txt
=> Update TT-NN to 0.57.0-rc2

requirements.txt
=> Update TT-NN to 0.57.0-rc15

requirements.txt
=> Update TT-NN to 0.57.0-rc16

requirements.txt
=> Update TT-NN to 0.57.0-rc17

requirements.txt
=> Update TT-NN to 0.57.0-rc22

requirements.txt
=> Update TT-NN to 0.57.0-rc26

requirements.txt
=> Update TT-NN to 0.57.0-rc29

requirements.txt
=> Update TT-NN to 0.57.0-rc40

.github/workflows/before_merge.yaml, requirements.txt
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/861)
Accuracy tests should run on a weekly basis instead of by each commit.
Created a new pipeline that will run the accuracy tests in the most parallel way possible
https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/14096153157
Also reused some code and removed the hardcoding of 40 groups
=> Implement pipeline to run accuracy tests

.github/workflows/before_merge.yaml, tests/models/detr/test_detr.py, tests/models/hardnet/test_hardnet.py, tests/models/unet/test_unet.py, tests/models/unet_brain/test_unet_brain.py, tests/models/yolov5/test_yolov5.py, tests/utils.py, tools/run_torchvision.py, tools/utils.py
Adds function to use cached model inputs with url backup Removes model validation that checks if we reference forked branch - this would often cause rate limit errors
=> Add NFS support for model tests

.github/workflows/before_merge.yaml, .github/workflows/run-accuracy-tests.yaml, tests/models/hand_landmark/test_hand_landmark.py
The previous PR was reverted due to permissions errors causing other CI runs to fail. This PR is largely based off of the last one, with some updates:
* Addressed feedback from previous PR
* Uses 22.04 as base image for docker container
* Updates new model accuracy workflow to use docker containers too
Previous PR description:
This makes the before_merge workflow run in a dockerized enviornment. The container is built on top of a container for Metal, has all the dependencies for the workflow built in.
The container is named: **ghcr.io/tenstorrent/pytorch2.0_ttnn/ubuntu-20.04-amd64:dev**
And is built on top of: **ghcr.io/tenstorrent/tt-metal/tt-metalium-ubuntu-20.04-amd64-release:latest-rc**
It is configured in the workflow like this:
`options: >- --rm -v …
=> Dockerize CI Tests

requirements.txt
=> Update TT-NN to 0.57.0-rc45

requirements.txt
=> Update TT-NN to 0.57.0-rc54

requirements.txt
=> Update TT-NN to 0.57.0-rc55

requirements.txt
=> Update TT-NN to 0.57.0-rc56

.github/workflows/run-accuracy-tests.yaml, .github/workflows/run-tests.yaml, tools/generate_op_accuracy_tests.py
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/861)
Test were not running at all, due some issues in the code generator
Fixed the code generator, that doesn't mean that all the tests are green, it means that now we can actually run them
=> Fixed accuracy tests

requirements.txt
=> Update TT-NN to 0.57.0-rc57

requirements.txt
=> Update TT-NN to 0.57.0-rc59

requirements.txt
=> Update TT-NN to 0.57.0-rc60

.github/workflows/run-tests.yaml, .github/workflows/update-readme.yaml
This adds support for automatic weekly updates for the README and model/OP docs
Additionally, this changes the flow to create the PR on a new branch
=> Update README automatically every week

requirements.txt, tests/lowering/eltwise/unary/test_tanh.py, tests/models/bloom/test_bloom.py, torch_ttnn/passes/lowering/target_wrappers.py
=> Update TT-NN to 0.57.0-rc63

requirements.txt
=> Update TT-NN to 0.58.0-rc6

requirements.txt
=> Update TT-NN to 0.58.0-rc11

tools/export_code.py
When running large models via the standalone code, there will commonly be errors relating to L1 OOM.
Typical error message:
```
Statically allocated circular buffers in program 539 clash with L1 buffers on core range [(x=0,y=0) - (x=6,y=7)]. L1 buffer allocated at 156544 and static circular buffer region ends at 176160
```
L1 OOM errors are fixed by deallocating the tensor once it no longer has any users. Pytorch does it when generating the string representation of the Python code ([link](https://github.com/pytorch/pytorch/blob/69e41cee04ca6c9b6fd4d15d8a0b72ce9b29c746/torch/fx/graph.py#L555-L581)). Typically code such as `; Tensor = None` is appended to the end of a line. This is usually through calling `graph.recompile()`. However, at the GraphModule level, there are no such metadata …
=> Add deallocation code for exported code to fix L1 OOM issues

dockerfile/Dockerfile, requirements.txt, torch_ttnn/passes/lowering/target_wrappers.py, torch_ttnn/passes/lowering/to_tt_pass.py
=> Update TT-NN to 0.59.0-rc5

requirements.txt
=> Update TT-NN to 0.59.0-rc9

requirements.txt
=> Update TT-NN to 0.59.0-rc11

requirements.txt
=> Update TT-NN to 0.59.0-rc13

requirements.txt
=> Update TT-NN to 0.59.0-rc15

requirements.txt
=> Update TT-NN to 0.61.0rc1.dev91
