- .github/workflows/hello-world.yaml
No ticket
We want to ensure that workflow is run on attempt to merge
I am following these tutorials to enable automated workflow run on an attempt to merge
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
> Enable workflow run on merge queues

- .github/workflows/before_merge.yaml
- README.md
- requirements.txt
- tests/test_cse.py
- tests/test_fall_back.py
- tests/test_if.py
- tests/test_more_ops.py
- tests/test_only_add_matmul.py
- tests/test_real_world.py
- tests/test_type_conversion.py
- tools/run_torchvision.py
- tools/run_transformers.py
- torch_ttnn/backend.py
- torch_ttnn/convert_type.py
- torch_ttnn/handle_input_aliasing.py
- torch_ttnn/mock_ttnn.py
- torch_ttnn/passes/add_data_move_pass.py
- torch_ttnn/passes/to_tt_pass.py
- torch_ttnn/patterns/add.py
- torch_ttnn/patterns/mm.py
- torch_ttnn/torch_stat.py
- torch_ttnn/utils.py
#10 
Trace the aten ops used by chosen LLM models and implement conversions to ttnn. Initial goal to run a "bert" model e2e with no or minimum fallback ops as possible.
- Add basic conversion for ops used by LLM models
- op usage: https://docs.google.com/spreadsheets/d/1fJuorhiQJo2ra5N_9Rv2zUNK2ZPSEOgycZ8YqhLocvk/edit?usp=sharing
- each conversion is accompanied by a unit test
- Fixes to match changes from tt-metal upstream
- Add demo for a couple of huggingface transformer models
> Add conversion for more OPs

- tests/test_expand.py
- torch_ttnn/passes/add_data_move_pass.py
- torch_ttnn/passes/to_tt_pass.py
Transform aten.expand by using ttnn.repeat. 
The interpretation of the `shape` argument between the two ops differ. For aten.expand the `shape` argument is the desired output shape. For ttnn.repeat the `shape` argument is a multiplier of the input shape instead. Therefore the shape information of the input tensor is needed.
* Add retention of shape metadata information for Placeholder nodes since transform() removes them
* Add missing metadata for conversions done under ReplaceMoreTtManually
* Implement the conversion from aten.expand using the shape metadata
In addition, ttnn.repeat acts differently between TILE and ROW_MAJOR layouts. In most cases, we would need to change the layout of a node to ROW_MAJOR before passing that to ttnn.repeat. Similarly, we would need to check if a layout …
> Implement conversion for aten.expand by using ttnn.repeat

- .gitignore
- tests/lowering/tensor_manipulation/test_aten_t.py
- tests/models/bert/test_bert.py
- tests/models/resnet/test_resnet.py
- tools/collect_metrics.py
- torch_ttnn/backend.py
- torch_ttnn/utils.py
Generate metrics that resembles the following example when running test models:
```
| Model   | Run Success | Torch Ops (Before)  | Torch Ops (Remains) | To/From_Device Ops | Original Run Time (s) | Compiled Run Time (s) | Accuracy          |
|---------|--------------|--------------------|---------------------|--------------------|-----------------------|-----------------------|-------------------|
| ResNet  | Yes          | 1234               | 567                 | 12                 | 0.45                  | 0.30                  | 85.5%             |
| VGG     | Yes          | 2345               | 890                 | 10                 | 0.50                  | 0.35                  | 92.1%             |
| BERT    | No           | 3456               | N/A                 | N/A …
```
> Add metrics collection

- README.md
- requirements-dev.txt
- tests/models/bloom/test_bloom.py
- tests/models/falcon/test_falcon.py
- tests/models/gpt2/test_gpt2.py
- tests/models/llama/test_llama.py
- tests/models/yolos/test_yolos.py
Added the following test models:
* bloom
* falcon
* gpt2
* llama
* yolos
Updated README to show the current status of the models
| Model         | Run Success   | Torch Ops (Before)   | Torch Ops (Remain)   | To/From_Device Ops   |   Original Run Time (s) | Compiled Run Time(s)   | Accuracy           |
|:--------------|:--------------|:---------------------|:---------------------|:---------------------|------------------------:|:-----------------------|:-------------------|
| Mnist (Eval)  | Yes           | 14                   | 5                    | 36                   |               0.0113227 | 2.2285212059505284     | 0.9871560472189823 |
| Mnist (Train) | Yes           | 14                   | 7                    | 42                   |               0.0120502 | …
> Add more transformer test models

- tests/models/bert/test_bert.py
- tests/models/bloom/test_bloom.py
- tests/models/falcon/test_falcon.py
- tests/models/gpt2/test_gpt2.py
- tests/models/llama/test_llama.py
- tests/models/mnist/test_mnist.py
- tests/models/resnet/test_resnet.py
- tests/models/yolos/test_yolos.py
- tools/collect_metrics.py
- torch_ttnn/backend.py
- torch_ttnn/metrics.py
- torch_ttnn/utils.py
* Move metrics collection to a new module
* Implement collection of schema information of all nodes, including input shapes and input values
* Generate a .csv that contains the input variations per op of the current models
> Generate schema metrics and input variation metrics

- README.md
- tests/lowering/eltwise/test_add.py
- tests/lowering/matmul/test_only_add_matmul.py
- tests/lowering/tensor_manipulation/test_aten_t.py
- tests/lowering/tensor_manipulation/test_expand.py
- tests/lowering/tensor_manipulation/test_transpose.py
- tests/lowering/tensor_manipulation/test_unsqueeze.py
- tests/lowering/test_if.py
- tests/lowering/test_more_ops.py
- tests/models/mnist/test_mnist.py
- tests/models/resnet/test_resnet.py
- tests/test_fall_back.py
- tools/collect_metrics.py
- torch_ttnn/metrics.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
* Fuse patterns of `to_device`, `to_layout`, and `from_torch` to just `from_torch`
* Fuse patterns of `from_device`, `to_layout`, and `to_torch` to just `to_torch`
* Remove checking of data movement ops in unit tests
* Instead of checking the nodes' exact positions in the graph, change to checking for their existences and relative positions to other nodes
* Update README to reflect changes
* Update mnist and resnet model tests to catch failures
* Add a warning when a model fails when collecting runtime metrics
* Fix metrics collection when original outputs are of Tensor type but compiled outputs are missing.
> Consolidate ttnn to/from data movement ops

- README.md
- docs/README.md.in
- tests/conftest.py
- tests/models/bert/test_bert.py
- tests/models/bloom/test_bloom.py
- tests/models/falcon/test_falcon.py
- tests/models/gpt2/test_gpt2.py
- tests/models/llama/test_llama.py
- tests/models/mnist/test_mnist.py
- tests/models/resnet/test_resnet.py
- tests/models/yolos/test_yolos.py
- tests/utils.py
- tools/collect_metrics.py
- torch_ttnn/metrics.py
* Add Pytest autouse fixture that compiles a model and records metrics for original and compiled run
* Models no longer need to import ttnn or torch_ttnn modules
* Models will need to register a few lines of information for this fixture to work
* Simplify the collect metrics script
* No longer need to hard-code a map of model paths
* No longer need to import output artifacts to calculate accuracy
* Accuracy is calculated in the pytest fixture directly
> Simplify testing of models to minimize extra code

- tests/lowering/eltwise/binary/test_div.py
- tests/lowering/eltwise/binary/test_eq.py
- tests/lowering/eltwise/binary/test_lt.py
- tests/lowering/eltwise/binary/test_sub.py
- tests/lowering/matmul/test_addmm.py
- tests/lowering/matmul/test_baddbmm.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- Restore node meta for intermediate nodes created during lowering of composite ops
- Add checks in composite op tests
> Preserve intermediate node meta for composite ops

- tests/lowering/creation/test_clone.py
- tests/lowering/eltwise/binary/test_div.py
- tests/lowering/eltwise/binary/test_lt.py
- tests/lowering/eltwise/binary/test_sub.py
- tests/lowering/eltwise/unary/test_clamp.py
- tests/lowering/eltwise/unary/test_gelu.py
- tests/lowering/eltwise/unary/test_pow.py
- tests/lowering/eltwise/unary/test_rsqrt.py
- tests/lowering/eltwise/unary/test_sigmoid.py
- tests/lowering/eltwise/unary/test_silu.py
- tests/lowering/matmul/test_addmm.py
- tests/lowering/matmul/test_baddbmm.py
- tests/lowering/matmul/test_only_add_matmul.py
- tests/lowering/normalization/test_layer_norm.py
- tests/lowering/pool/test_avg_pool_2d.py
- tests/lowering/reduction/test_mean.py
- tests/lowering/tensor_manipulation/test_aten_t.py
- tests/lowering/tensor_manipulation/test_transpose.py
- tests/test_fall_back.py
- tests/utils.py
The tests were not using assert correctly. This PR will follow the assertion from tt-metal unit tests.
Also fix avg_pool_2d test from the tt-metal unit test example.
> Fix assertion with unit tests

- README.md
- docs/README.md.in
- tests/conftest.py
- tests/models/falcon/test_falcon.py
- tests/models/gpt2/test_gpt2.py
- tests/pytest.ini
When we introduce a model test, we want to ensure that the torch/CPU version runs. The compiled version may be expected to fail at this time. The `torch_only` mark will raise an `pytest.xfail` instead of the normal exception when compiled run fails.
> Add torch_only marker to mark compiled run as xfail but leave torch run as normal

- requirements-dev.txt
- tests/models/glpn_kitti/test_glpn_kitti.py
None
The test fails for now:
```
self = <OpOverload(op='aten.convolution', overload='default')>
args = (TorchTensor([[[[-0.3418, -0.1445, -0.3398,  ...,  0.0801, -0.0059,  0.0332],
[-0.4160, -0.8438, -0.964...2.0743,  0.1114, -0.0142,  0.0484, -0.3084,  0.2446, -0.5519],
requires_grad=True), [8, 8], [0, 0], [1, 1], ...)
kwargs = {}
def __call__(self, *args, **kwargs):
>       return self._op(*args, **(kwargs or {}))
E       RuntimeError: expected scalar type BFloat16 but found Float
../tt-metal/python_env/lib/python3.8/site-packages/torch/_ops.py:513: RuntimeError
```
Add test for GLPN-KITTI
https://huggingface.co/vinvino02/glpn-kitti
> Test GLPN-KITTI

- README.md
- docs/README.md.in
- tests/conftest.py
- tests/models/t5/test_t5.py
- torch_ttnn/metrics.py
`model.generate` can be passed into `torch.compile` without any changes to the current backend. This commit will display better error messages if the torch rerun failed due to mismatch between `model.generate`, `model`, and the inputs.
> Add support for model.generate with T5 model

- requirements-dev.txt
- tests/models/openpose/test_openpose_v2.py
Link to Github Issue
The current OpenPose test does not work because the model in use is not supported by the PyTorch Dynamo compiler flow. 
I suspect the issue is due to the model's use of dynamic shapes, which the current PyTorch Dynamo compilation flow does not support well. My assumption is based on the error message during compilation.
```
E       torch._dynamo.exc.BackendCompilerFailed: backend='ttnn_backend' raised:
E       RuntimeError: aten::clone() Expected a value of type 'Tensor' for argument 'self' but instead found type 'SymInt'.
E       Position: 0
E       Value: s1
E       Declaration: aten::clone(Tensor self, *, MemoryFormat? memory_format=None) -> Tensor
E       Cast error details: Unable to cast s1 to Tensor
E
E       While executing %clone_default_1 : [num_users=1] = …
```
> Model OpenPose.

- tests/models/segment_anything/test_segment_anything.py
None
Add model segment-anything to trace. 
However, unfortunately the goal is not achieved. We decided to push the code just for keeping a record, and we marked the test skipped.
The test fails to run because it requires installation of package sam2, but sam2 requires Python>=3.10.0 while the default version on Ubuntu 20.04 is 3.8. 
We tried to find alternative pytorch implementation of the same model but found nothing.
Add model segment-anything.
> Model segment-anything.

- .github/workflows/update-ttnn-wheel.yaml
- requirements.txt
- tools/huggingface_delete_cache.py
- torch_ttnn/backend.py
- torch_ttnn/passes/lowering/target_wrappers.py
None
Several PRs require latest version of Metal wheel
Bumping the TT-NN dependency.
Fixing lowering issue.
```
E       TypeError: __call__(): incompatible function arguments. The following argument types are supported:
E           1. (self: ttnn._ttnn.operations.data_movement.clone_t, input_tensor: ttnn._ttnn.deprecated.tensor.Tensor, *, memory_config: Optional[ttnn._ttnn.deprecated.tensor.MemoryConfig] = None, dtype: Optional[ttnn._ttnn.deprecated.tensor.DataType] = None, queue_id: int = 0) -> ttnn._ttnn.deprecated.tensor.Tensor
E       
E       Invoked with: <ttnn._ttnn.operations.data_movement.clone_t object at 0x7f53506ff570>, ttnn.Tensor([[ 0.51562,  1.50781,  ...,  0.00000,  0.00000],
E                    [ 1.39844,  1.61719,  ...,  0.00000,  0.00000],
E                    ...,
E …
```
> Bump metal to latest available wheel build. Fix ttnn.clone usage

- tests/lowering/normalization/test_log_softmax.py
- torch_ttnn/passes/lowering/to_tt_pass.py
None
Lower `aten._log_softmax`
We might encounter issues about numerical stability in the future by splitting `log_softmax`, but this is the best we can do for now.
> Convert `aten._log_softmax`

- tests/lowering/tensor_manipulation/test_constant_pad_nd.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
For currently unsupported front padding: #192
Convert `constant_pad_nd` into `ttnn.pad`. It supports padding tile-size aligned tensor in `TILE_LAYOUT` directly; otherwise it converts the non-aligned tensor into `ROW_MAJOR_LAYOUT` first then pad
Currently it doesn't support front padding and fallbacks to aten.
- Conversion from `aten.constant_pad_nd` to `ttnn.pad`
- Add `ttnn.pad` and `ttnn.to_layout` to `TTNN_DATAMOVE_OPS` for inserting data movement
- Test cases for the conversion
> Convert `constant_pad_nd` into `ttnn.pad`

- tests/conftest.py
- tests/lowering/eltwise/unary/test_floor.py
- tests/lowering/misc/test_fallback_incompatible_platform.py
- tests/pytest.ini
- torch_ttnn/backend.py
- torch_ttnn/passes/lowering/to_tt_pass.py
None
Some ttnn ops do not run on Grayskull like `ttnn.floor`
> Add skip and fallback for ops not supported by Grayskull

- tests/lowering/eltwise/unary/test_remainder.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
None
Convert `aten.remainder.Scalar` to `ttnn.remainder`
- Add conversion from `aten.remainder.Scalar` to `ttnn.remainder`
- Test cases for the conversion
> Convert `aten.remainder.Scalar` to `ttnn.remainder`

- requirements.txt
> Update TT-NN to 0.52.0-rc28

- tests/lowering/tensor_manipulation/test_view.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/173
Currently, `aten.view` falls back to `aten.reshape`. 
Add conversion to `ttnn.reshape` based on supported shapes. 
BERT has the following input variations. The unchecked boxes indicate fallback to `aten.reshape`.
There are currently 2 unsupported shapes. TTNN team is currently looking to add support: https://github.com/tenstorrent/tt-metal/issues/12715
> Convert `aten.view` to `ttnn.reshape`

- tests/conftest.py
- tests/models/mnist/test_mnist.py
None
After reviewing `test_mnist.py` as an example of testing the training mode, I noticed that it lacks a test for the backward pass, which calculates the gradients. I've rewritten the test, and if you agree with this change, I plan to apply the same approach to all other training tests.
* The training test in `test_mnist.py`.
* The training process in `conftest.py`.
> Enhance mnist training test.

- requirements.txt
> Update TT-NN to 0.52.0-rc32

- tests/lowering/embedding/test_embedding.py
- tests/models/squeeze_bert/test_squeeze_bert.py
- torch_ttnn/passes/lowering/to_tt_pass.py
n/a
ttnn embedding does not support input where the last dimension is not a multiple of TILE_SIZE.
In to_tt_pass use ttnn embedding only if input does have last dim a multiple of TILE_SIZE, otherwise use torch fallback.
> Add fallback for embedding in to_tt_pass

- tests/conftest.py
- tests/models/mnist/test_mnist.py
- tests/utils.py
#269
The `compile_and_run` fixture will run model with torch_ttnn backend if set torch_ttnn property, but for the training mode it needs to append fake loss function and do the backward, which may differ from models, so needs a method to deal this part.
Implement `ModelTester` class, which handle the `test_model` method, and which do the forward for eval mode and do both forward & backward for training mode, and do the compilation if true the `as_ttnn` arg.`test_model` method also handle the model & input adjustment from different mode.
After this refactor, the testcase under `tests/models` should inherit `ModelTester` class and implement the `_load_model` & `_load_input` method. If other method like `append_fake_loss_function` is not appropriate for current test, can also override it.
So …
> Refactor test model

- requirements.txt
> Update TT-NN to 0.53.0-rc6

- .github/workflows/before_merge.yaml
- tests/conftest.py
- tests/utils.py
- tools/aten_test.tmpl
- tools/generate_input_variation_test_from_models.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/249
To implement the script of generate input variations test
As the ticket says, it want to make all input varations as tests from [the input variations doc](https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/docs/cumulative_input_variations.md#atenrepeatdefault)
I study the code of collect-metrics job, seems it use `InputVarPerOp::write_md_for_input_variations` to generate the input variations doc, so I think use `InputVarPerOp` to collect all model metrics, and its recorded input variations will consistent with the input variations doc, so I reuse these data structure of `InputVarPerOp`.
Currently, the test flow of generated input variation test is:
0. convert input variation string as randomized value
1. inference before …
> Generate tests/input_variations

- tests/models/clip/test_clip.py
- tools/aten_test.tmpl
- torch_ttnn/metrics.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#302
Let `test_clip.py` pass
- Add `torch_ttnn/passes/lowering/to_tt_guard.py` to check if node can lowering to ttnn op by its input shape
- Based on `tests/input-variations/CLIP/`, write the guard function
- remove `pytest.mark.compilation_xfail` from `test_clip.py`
Before this PR, the status of single op test is
```
tests/input-variations/CLIP/test_aten__softmax_default.py ..                                               [  1%]
tests/input-variations/CLIP/test_aten__to_copy_default.py .....                                            [  6%]
tests/input-variations/CLIP/test_aten__unsafe_view_default.py ..                                           [  8%]
tests/input-variations/CLIP/test_aten_add_Tensor.py ....                                                   [ 11%] …
```
> Remove xfail from Clip model

- tests/lowering/tensor_manipulation/test_permute.py
- tests/lowering/tensor_manipulation/test_transpose.py
- torch_ttnn/passes/lowering/to_tt_pass.py
Lower OPs from Group B to fewer TTNN OPs. OPs in this group are
aten.t.default.md
aten.transpose.int.md
aten.permute.default.md
In `to_tt_pass` all three are already lowered to `ttnn.permute`. 
This PR adds workaround for issue https://github.com/tenstorrent/tt-metal/issues/11191 that is used for `transpose` also to `permute`.
> TM Lowering Group B

- tests/lowering/tensor_manipulation/test_squeeze.py
- torch_ttnn/backend.py
- torch_ttnn/passes/lowering/to_tt_pass.py
Lower OPs from Group C to fewer TTNN OPs. OPs in this group are
```
aten.view.default.md
aten.unsqueeze.default.md
aten.squeeze.dim.md
aten._unsafe_view.default.md
```
In `to_ttnn_pass` `unsqueeze`, `view` and `unsafe_view` are already lowered to `ttnn.reshape`.
Added lowering of `squeeze` to `ttnn.reshape`  and added flag `use_less_ttnn_op_types` to class `TorchTtnnOption` to enable this lowering.
> TM Lowering Group C

- .github/workflows/before_merge.yaml
N/A
I need to download CI artifacts for development, for example, push the auto generated guard function from all models needs all the single op test result.
But there needs to download 40 times of artifacts to get all the result, so I add a job that collect these artifacts into one artifact.
Add CI job named collect-artifacts-from-matrix-jobs
> [CI] collect artifacts from matrix jobs

- tests/utils.py
- tools/aten_test.tmpl
- tools/generate_guard_function_from_input_var_metric.py
- tools/generate_input_variation_test_from_models.py
- tools/to_tt_guard.tmpl
- torch_ttnn/passes/lowering/to_tt_guard.py
#320 
see #320
- Implement `tools/generate_guard_function_from_input_var_metric.py` to parse failed cases from `metrics-input-variations/` folder and export `to_tt_guard.py`
- Update `to_tt_guard.py`
- The `metrics-input-variations/` data used is downloaded from [this pipeline](https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/11378530820), specifically from `model-input-variations-tests-metrics` artifact
- The failed threshold is set with ["run", "accuracy"], which mean a case is considered failed if either these checks fail:
- run: failed to run compiled model
- accuracy: the accuracy between original and compiled model is not close
I will check how many model tests pass and remove its `compilation_xfail` for the next PR
> Implement tool to automatically generate guard function

- tests/models/MobileNetV2/test_MobileNetV2.py
- tests/models/albert/test_albert_masked_lm.py
- tests/models/albert/test_albert_question_answering.py
- tests/models/albert/test_albert_sequence_classification.py
- tests/models/albert/test_albert_token_classification.py
- tests/models/codegen/test_codegen.py
- tests/models/detr/test_detr.py
- tests/models/distilbert/test_distilbert.py
- tests/models/dpr/test_dpr.py
- tests/models/flan_t5/test_flan_t5.py
- tests/models/glpn_kitti/test_glpn_kitti.py
- tests/models/gpt_neo/test_gpt_neo.py
- tests/models/llama/test_llama.py
- tests/models/mobilenet_ssd/test_mobilenet_ssd.py
- tests/models/musicgen_small/test_musicgen_small.py
- tests/models/opt/test_opt.py
- tests/models/perceiver_io/test_perceiver_io.py
- tests/models/roberta/test_roberta.py
- tests/models/speecht5_tts/test_speecht5_tts.py
- tests/models/stable_diffusion/test_stable_diffusion_v2.py
- tests/models/t5/test_t5.py
- tests/models/timm/test_timm_image_classification.py
- tests/models/torchvision/test_torchvision_image_classification.py
- tests/models/torchvision/test_torchvision_object_detection.py
- tests/models/vilt/test_vilt.py
- tests/models/whisper/test_whisper.py
- tests/models/xglm/test_xglm.py
- tests/models/yolos/test_yolos.py
- tests/models/yolov3/test_yolov3.py
- tests/models/yolov5/test_yolov5.py
N/A
ttnn op is support bf16 type, so if the model not set to bf16, its weight may be float type, then the ttnn op will failed.
There still many model test not set to bf16 type, so set it to bf16 type
- Model test value type set to bf16
- Fix model test script which inference method is using model.generate
- After model set to bf16, some test pass (almost from torchvision). Now the pass rate become `52.6% (80/152)`
> Model test value type set to bf16

- .github/workflows/before_merge.yaml
- tools/generate_input_variation_test_from_models.py
N/A
for example, `ghostnet_100.in1k.py` is not a legal script name for pytest, fix it to `ghostnet_100_in1k.py`
- fix `generate_input_variation_test_from_models.py` and add merge feature
- fix typo of `before_merge.yaml`
> Fix generate_input_variation_test_from_models.py

- .github/workflows/before_merge.yaml
- .github/workflows/before_merge2.yaml
N/A
As mentioned in [here](https://github.com/tenstorrent/pytorch2.0_ttnn/pull/332#issuecomment-2434700680), let `model-tests` & `model-autogen-op-tests` parallel run in the same stage
- Let `model-tests` & `model-autogen-op-tests` parallel run in the same stage
- Let `model-autogen-op-tests` triggered only if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_report != 'None'}}
> CI parallel autogen op

- .github/workflows/before_merge.yaml
- tools/generate_guard_function_from_input_var_metric.py
- tools/generate_input_variation_test_from_models.py
N/A
- I wrongly push single op test as `tests/autogen_op` (it should be `tests/autogen-op`), but I don't want to rename it again, so edit the script to align `tests/autogen_op`
- add splits & group to fix model-autogen-op-tests
- gen single op tests in push-autogen-op-tests
- Rename `tests/autogen-op` as `tests/autogen_op`
- Fix model-autogen-op-tests
- Fix push-autogen-op-tests
> Fix before_merge

- tools/collect_metrics.py
N/A
To simpify the report of single op column
mapping old single op column as
```
Isolated:
Unknown => single-native-run failed
Fail => single-run failed
Done => single-run pass & single-converted pass
Fallback => single-run pass & single-converted failed
None => Don't have result of single op test
PCC => status of single-accuracy
```
> Simply op report

- requirements.txt
> Update TT-NN to 0.53.0-rc28

- tests/lowering/tensor_manipulation/test_aten_t.py
- tests/lowering/tensor_manipulation/test_transpose.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#377
Enable `aten.t.default` conversion for more cases and fallback for the issue mentioned in #377
- Explicitly handle unsupported cases in `to_tt_pass.py`
- Remove `aten.t.default` from blocklist
- Add tests to verify support and unsupported cases
> Enable `aten.t.default` conversion for more cases

- docs/README.md.in
- tests/lowering/creation/test_arange.py
- torch_ttnn/backend.py
- torch_ttnn/passes/constant_folding_pass.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
some models contain operations that have known constant arguments (inputs) before compiling, such operations could be transformed (fold) into constant values to simplify model graph.
Implement a `ConstantFolder` that handles folded operations.
For now, support operations are
- torch.ops.aten.lift_fresh_copy.default,
- torch.ops.aten.pow.Tensor_Tensor
- torch.ops.aten.arange.start
- torch.ops.aten.unsqueeze.default
cc @swimdi @jdh8
> Implement ConstantFoldingPass

- tests/conftest.py
N/A
I need to download `model-tests-metrics` from CI to refresh google sheet report, but its size is 400 MB and spent me 10 min. Most of the size is from the graphviz, I want to disable it to speed up the download time
Disable gen_graphviz in conftest
> Disable gen_graphviz in conftest

- tests/lowering/embedding/test_embedding.py
- torch_ttnn/passes/lowering/to_tt_pass.py
None
For `aten.embedding`, support tensors with innermost dimension not a multiple of the tile.
Keep using tile layout if the size is a multiple of the tile.  Use row-major layout otherwise, for previously unsupported cases.
> General conversion for `aten.embedding`

- .github/workflows/before_merge.yaml
- torch_ttnn/passes/lowering/add_data_move_pass.py
N/A
There's an example element in `metrics/xxx/compiled-schema_list.pickle`
```
{'opname': 'ttnn.add', 
'original_inputs': {'opname': 'aten.add.Tensor', 'inputs': ['Tensor<[2, 3]> self = ?', 'Tensor<[2, 3]> other = ?']}}
```
And the `collect_metrics.py` will parse it to check whether original aten op is converted to ttnn op
And the code of [`add_data_move_pass.py`](https://github.com/tenstorrent/pytorch2.0_ttnn/blob/a26823e8ab290f5142a2d9417f1cd8b32375e7d7/torch_ttnn/passes/lowering/add_data_move_pass.py#L222)
```
def try_call_aten__to_copy_with_meta(g, to_torch_node):
if hasattr(to_torch_node, "meta") and "val" in to_torch_node.meta and hasattr(to_torch_node.meta["val"], "dtype"):
dtype = to_torch_node.meta["val"].dtype
call_func = g.call_function(
torch.ops.aten._to_copy.default, …
```
> Fix docs OP report

- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
In Bloom model, the `torch.ops.aten.expand.default` op should lower to `ttnn.expand` rather than `repeat`.
Fix the logic of checking if could lowering to `ttnn.expand`.
> Fix lowering to ttnn.expand logic error

- tests/pattern/test_beit_train_pattern.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
ttnn.mean does not support keep_dim=False but aten.mean does. Append reshape to workaround
- Fix aten.mean lowering when keep_dim=False
- Remove all `aten_mean_dim_blocklist`
- Add `test_beit_train_pattern.py` because I found this bug from beit
I'll merge #422 first then this PR
> Fix aten.mean lowering when keep_dim=False

- tests/lowering/creation/test_masked_fill.py
- tests/lowering/pool/test_avg_pool_2d.py
#458
Temporarily disable failing tests `test_adaptive_avg_pool_2d` and `test_masked_fill`
- Skip tests of `test_adaptive_avg_pool_2d` and `test_masked_fill`
> Temporarily disable failing tests

- tests/lowering/misc/test_if.py
- tests/lowering/misc/test_sum.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
`torch.ops.aten.sum.default` should be lowering to `ttnn.sum` if possible.
`torch.ops.aten.sum.default` can be replaced by `ttnn.sum` and a `torch.ops.aten.squeeze.default`.
Because `torch.ops.aten.sum.default` will sum out to rank 0 result, an auxiliary `torch.ops.aten.squeeze.default` op is required to reach original result tensor.
- test
```
pytest -s tests/lowering/misc/test_sum.py
```
> Implement `torch.ops.aten.sum.default` lowering to `ttnn.sum`

- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#386 
I was going to support unsqueeze guided by [here](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/386#issuecomment-2479097908), but I found latest tt-metal already support all input variation except zero element num, so I just relax the unsqueeze lowering constraint and it's now fully lowered in llama 
- Relax lowering constraint of unsqueeze
- Add guard of GPTNeo
> Relax unsqueeze

- tests/lowering/embedding/test_embedding.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
Fix a particular case in #407
There is a failing generated test case for conversion to `ttnn.embedding`:
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/8b7d5ce619a6b3d86900cbdbfc1c0d0e33a676c5/torch_ttnn/passes/lowering/to_tt_guard_autogen.py#L239
The argument `indices` does not have a known shape.  This triggered a runtime error.
Gracefully run the untiled algorithm when the shape of `indices` is unknown.
> Fix `ttnn.embedding` when the shape of `indices` is unknown

- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
1. Lowering `aten.select.int` should consider the negative index
2. float type `to_torch` no need to insert additional `aten._to_copy`
1. Lowering `aten.select.int` op will legalize negative index then set to TTNN op.
2. If dtype of  `to_torch` op in is **torch.float32**, **torch.float64**, **torch.bfloat16**, then skip `aten._to_copy` creation.
> Fix `aten.select.int` lowering issue and remove additional `aten._to_copy` op creation

- tests/lowering/tensor_manipulation/test_aten_t.py
- tests/lowering/tensor_manipulation/test_transpose.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#439
`ttnn.transpose` has been improved to support all use cases of `aten.t.default` and `aten.tranpose.int`. Use it instead of `ttnn.permute`
- Convert `aten.t.default` and `aten.tranpose.int` into `ttnn.tranpose`
- Enable all tests
> Use `ttnn.transpose` for aten transpose ops

- tests/lowering/eltwise/unary/test_hardsigmoid.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- Resolves #480
Compile `aten.hardsigmoid` to `ttnn.sigmoid`:
https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html
> Convert `aten.hardsigmoid` to `ttnn.hardsigmoid`

- .github/workflows/before_merge.yaml
- torch_ttnn/passes/lowering/add_data_move_pass.py
N/A
- In `push-autogen-op-tests`, nothing to commit but run `git push` cause it failed
- `call_func.meta = src_node.meta` assign the reference so the later `call_func.meta["original_input_variations"] = None` also infect `src_node.meta`, and then it cause input variation report the wrong status
- Fix `push-autogen-op-tests` job failed if workflow set `Docs`
- Fix input variation report the wrong status
> Fix push-autogen-op-tests job failed and input variation report the wrong status

- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/486
Some `torch.ops.aten.slice.Tensor` ops are guarded from lowering to `ttnn.slice`.
Remove all `torch.ops.aten.slice.Tensor` block list in guard function.
> Enable all `torch.ops.aten.slice.Tensor` lowering to `ttnn.slice`

- tests/conftest.py
- tests/models/detr/test_detr.py
- tests/models/distilbert/test_distilbert.py
- tests/models/dpr/test_dpr.py
- tests/models/gpt2/test_gpt2.py
- tests/models/hand_landmark/test_hand_landmark.py
- tests/models/mlpmixer/test_mlpmixer.py
- tests/models/roberta/test_roberta.py
- tests/models/segformer/test_segformer.py
- tests/models/yolov3/test_yolov3.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
Sweep the ❌ models and try to let it 🚧, now remains these 15 ❌ models that is hard to 🚧 by blocklist
| model | issue |
|---|---|
| GPTNeo | result nan #503 |
| codegen | SymInt #524 |
| FLAN-T5 | SymInt #524 |
| GLPN-KITTI | shape differ #390 |
| OPT | SymInt #524 |
| t5-small | SymInt #524 |
| t5-base | SymInt #524 |
| t5-large | SymInt #524 |
| MobileNetSSD | nms_kernel needs float #525 |
| ssd300_vgg16 | nms_kernel needs float #525 |
| ssdlite320_mobilenet_v3_large | nms_kernel needs float #525 |
| retinanet_resnet50_fpn | nms_kernel needs float #525 |
| retinanet_resnet50_fpn_v2 | nms_kernel needs float #525 |
| Whisper | SymInt #524 |
| Stable Diffusion V2 | test time too long, postpone |
- Remove some `@pytest.mark.compilation_xfail`
- Add blocklist to try to let model 🚧
> Sweep the ❌ models(no train)

- tests/lowering/tensor_manipulation/test_slice_scatter.py
- torch_ttnn/passes/lowering/to_tt_pass.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/485
`torch.ops.aten.slice_scatter.default`  remains not lowering to TTNN.
`torch.ops.aten.slice_scatter.default(input, src, dim, start, end)` could be lowered into `ttnn.slice` + `ttnn.concat`
or
just return `src` tensor, if size of `src` tensor == size of `input` tensor
The only 2 models, **ghostnet_100.in1k** and **ghostnetv2_100.in1k** which has `torch.ops.aten.slice_scatter.default` op are the case of just return `src` tensor
Test
```bash
pytest -s tests/lowering/tensor_manipulation/test_slice_scatter.py
```
> Enable `torch.ops.aten.slice_scatter.default`  lowering

- tests/pattern/test_vgg_pattern.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#475 
Current lowering of `aten._adaptive_avg_pool2d.default` is wrong, and `ttnn.avg_pool2d` is not finished according to https://github.com/tenstorrent/tt-metal/issues/12151, so disable its lowering
Additionally, some special input varation let `aten._adaptive_avg_pool2d.default` do nothing, add the code to detect it and bypass it
- Disable lowering of `aten._adaptive_avg_pool2d.default`
- Check special input variation pattern of aten._adaptive_avg_pool2d.default
- Remove blocklist of `aten._adaptive_avg_pool2d.default`
> Fix lowering of aten._adaptive_avg_pool2d.default

- tests/lowering/pool/test_max_pool_2d.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#430, https://github.com/tenstorrent/tt-metal/issues/13901
With the recent change https://github.com/tenstorrent/tt-metal/commit/8dee2c21618a386a121663632241a871f06a1765, we can relax the constraint of non-pow-of-2 channels of `max_pool2d` to "be divisible by TILE_SIZE * 8 when > TILE_SIE * 8"
- Relax the constraint of non-pow-of-2 channels of `max_pool2d`
- Update test cases
> Relax max_pool2d constraints for non-pow-of-2 channels

- tests/pattern/test_data_move_reuse_pattern.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
Although this pass named `add_data_move`, but put things in perspective, if each node can ensure its input correct, then it also ensure the input is added the appropriate data movement node
So in there introduce `NodeInputAligner` class, which help node's input  **`align`** to the correct posture
In torch_ttnn compiler, the main task of `NodeInputAligner` to deal with has these scope
1. torch to ttnn: key action is `from_torch`
2. ttnn to torch: key action is `to_torch`
worth noting, some ttnn node may needs different layout & device, so also have this scope
3. ttnn to ttnn: key action is `to_layout` and (`from_device` or `to_device`)
for example, if reshape input is `tile_layout`,then the input needs be aligned using `_align_for_special_layout`
```
input_node => …
```
> Refactor add data move pass

- torch_ttnn/passes/constant_folding_pass.py
N/A
Adding new foldable operation in `ConstantFoldingPass` could be cumbersome
1. Add operation in `self.foldable_ops` set
2. Implement operation evaluation method in `_evaluate_node`
Revise `_evaluate_node`, using common evolution method for most of operations.
Future, new foldable operation just to add in `self.foldable_ops`.
> Simplify _evaluate_node in constant folding pass

- tests/lowering/tensor_manipulation/test_transpose.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/543
1. `aten.transpose.int` operation not lowering to TTNN
2. tensor with rank > 4 could not support by `ttnn.transpose`
1. Remove `aten.transpose.int` op guarding block list
2. Try do `ttnn.reshape->ttnn.transpose->ttnn.reshape` to do transpose tensor of rank > 4
> Lowering transpose 

- tests/pattern/test_nms_pattern.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/utils.py
#525 
Now `ttnn.to_torch` can specifiy dtype ([suggested in there](https://github.com/tenstorrent/pytorch2.0_ttnn/pull/383)), so remove `aten._to_copy` and let `to_torch` carry out its intention, and then #525 fixed
- Remove `aten._to_copy` and let `ttnn.to_torch` specify dtype
> Remove `aten._to_copy` and let `ttnn.to_torch` specify dtype

- tests/lowering/eltwise/binary/test_div.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- Resolves #479 
- Relates to tenstorrent/tt-metal#15630
Remove the blocklist for `aten.div.Tensor` and make sure these cases pass
> Remove the blocklist for `aten.div.Tensor`

- tests/lowering/creation/test_ones.py
- torch_ttnn/passes/constant_folding_pass.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/572
Some `aten.ones.default` op remains.
Most `aten.ones.default` op has constant input shape to create ones tensor, it could be constant folding.
1. Add constant folding for `aten.ones.default`
2. Remove guard block
> constant folding for `aten.ones.default` and remove guard blocklist

- torch_ttnn/passes/lowering/to_tt_pass.py
- torch_ttnn/utils.py
N/A
Some ✅ modes become 🚧 
- BERT
- SqueezeBERT
- Perceiver IO
- albert/albert-base-v2-classification
- twmkn9/albert-base-v2-squad2
And the reason is `aten.add/mul` become not lowered
I think the root cause is because `get_shape(node)` not handle the scalar case
- Let `get_shape(node)` handle the arg is scalar case, and above model is back to ✅
> Fix some `aten.add/mul` not lowered

- tests/lowering/creation/test_full_like.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#589
Decompose `aten.full_like` into `aten.full`. There is one remaining dynamic shape case is not supported yet and guarded
- Decompose `aten.full_like` into `aten.full`
- Add tests
> Decompose `aten.full_like` into `aten.full`

- torch_ttnn/passes/lowering/to_tt_pass.py
- torch_ttnn/utils.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/610
`get_shape` function could not properly deal with `get_attr` op
Get correct tensor shape of `get_attr` op.
> Get correct tensor shape of `get_attr` op

- tests/lowering/creation/test_full.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/588
Remove all guards of `aten.full` as all cases can pass now
- Remove all guards of `aten.full`
- Add some tests for `aten.full`
> Remove guards of `aten.full`

- tests/pattern/test_detr.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#595 
Fix lowering of split and identify this issue
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/61de9b9f12ef7645ef2c729a988a38f188c98305/torch_ttnn/passes/lowering/to_tt_pass.py#L778-L782
- Fix split lowering
- Remove aten_split_Tensor_blocklist
> Fix `aten.split.Tensor` lowering

- tests/lowering/creation/test_zeros_like.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#630, #280
Remove `aten.zeros_like` autogen blocklist. The 1-D output shape is fallback currently because tile layout tensor is always 2D currently (#280)
- Remove `aten_zeros_like` autogen blocklist
- Guard 1-D output shape cases in `to_tt_pass.py`
- Add more test cases
> Remove `aten.zeros_like` autogen blocklist and guards unsupported cases

- tests/pattern/test_beit_pattern.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard.py
#420 
- from_torch not as bfloat16 if val type is int and its user is reshape
- from_torch not as bfloat16 if val type is int and its user is reshape
I'll merge #532 first then this PR
> Fix reshape value error too large

- torch_ttnn/passes/constant_folding_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
For operations that has input of iterable type, fails to constant folding. eg,
```
%_unsafe_index_tensor : [num_users=1] = call_function[target=torch.ops.aten._unsafe_index.Tensor](args = (%_folded__to_copy, [None, None, %_folded_unsqueeze_1, %_folded__to_copy_2]), kwargs = {})
```
Handle the check fold and evaluate fold for iterable types (list, tuple, torch.fx.immutable_collections.immutable_list).
> constant folding to handle tensor arguments of iterable type

- tests/lowering/creation/test_new_full.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#647
Convert `aten.new_full` to `aten.full`
- Convert `aten.new_full` to `aten.full`
- Add tests
> Convert `aten.new_full` to `aten.full`

- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
`torch.ops.aten.select.int` and `torch.ops.aten.sum.default` will generated aten op in lowered function, move it to `decompose_aten_to_aten_ops` as possible. `torch.ops.aten.sum.default` cannot fully moved to, so add `again` to check
`aten.select.int` and `aten.sum.default` will generate ATen operations in the lowered function. The former can moved to `decompose_aten_to_aten_ops` but later cannot, so add an `again` mechanism
Edit `torch.ops.aten.select.int` and `torch.ops.aten.sum.default`
> Move lowered with aten to decompose as possible

- tests/lowering/tensor_manipulation/test_as_strided.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- Partially resolves #587
As per discussion in #587, we only convert `aten.as_strided` that is equivalent to `ttnn.reshape`.  This would convert all our known input variations for now.
> A general implementation is best done as a kernel op. Its element rearrangement is far more complicated than slicing. https://pytorch.org/docs/stable/generated/torch.as_strided.html
> 
> However, our use cases can be simplified into `reshape`. The `stride` argument matches the default strides of `size` for each case. I am working on a conversion that only lowers these cases. https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/docs/operations/aten.as_strided.default.md
> Lower `aten.as_strided` when it can be simplified into `ttnn.reshape`

- tests/lowering/eltwise/binary/test_floor_divide.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- Resolves #638
I found that `ttnn.floor_div` is only accurate when its divisor is a power of 2.  Luckily, our only input variation has 2 as divisor.
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/7ee612585811e6f6d6718f9f13a1ec4376ab1ce9/docs/operations/aten.floor_divide.default.md
Implemented the conversion and added some test cases
> Lower `aten.floor_divide` to `ttnn.floor_div`

- tests/lowering/eltwise/ternary/test_where.py
- Resolves #597
- Depends on tenstorrent/tt-metal#16254
`ttnn.where` cannot take 0-D tensors just like the other elementwise ops.  I am working on a ticket,
Add test cases to watch out the concerned input variations
> Test `ttnn.where` with concerned cases

- tests/lowering/conv/test_conv.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/target_wrappers.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#429
Convert aten convolution 1d cases to `ttnn.Conv1d`
- Refactor aten.convolution conversion to support conv1d and conv2d
- Add tests
> Convert aten convolution 1d cases to `ttnn.Conv1d`

- tests/lowering/pool/test_max_pool_2d.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#430
Remove OOM guard for `aten.max_pool2d_with_indices.default` as those shapes passed now
- Remove OOM guard for `aten.max_pool2d_with_indices.default`
> Remove OOM guard for `aten.max_pool2d_with_indices.default`

- tests/lowering/misc/test_index.py
- tests/lowering/misc/test_index_select.py
- tests/utils.py
- torch_ttnn/passes/constant_folding_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
#535 
#544 
#639 
Some input variation of index like below can be replaced as embedding
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/217470993d314925a6473fe3511081d03d7f1ef8/tests/autogen_op/ALL/test_ALL_aten_index_Tensor.py#L45-L59
So add the conversion of it
- Convert some case from index to embedding
- Convert `aten.index_select.Tensor` to `aten.index.Tensor`
- Add `aten.index_select.Tensor` and `aten.index.Tensor` to const fold pass
credit: @jerrysky3
> Convert some index case to embedding

- tests/conftest.py
- tests/models/torchvision/test_torchvision_object_detection.py
- tests/pytest.ini
- torch_ttnn/passes/lowering/to_tt_guard.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
N/A
Sweep the ❌ models again and do some fix, now remains these 9 ❌ models 
| model | issue |
|---|---|
| FLAN-T5 | SymInt #524 |
| GPTNeo | SymInt #524 |
| OPT | SymInt #524 |
| Stable Diffusion V2 |  not contiguous #688 |
| Whisper | SymInt #524 |
| codegen | IndexError #689 |
| t5-small | SymInt #524 |
| t5-base | SymInt #524 |
| t5-large | SymInt #524 |
- Fix `aten.repeat`
- add some guard
> Sweep the ❌ models again(no train)

- requirements.txt
> Update TT-NN to 0.56.0-rc9

- .github/workflows/update-ttnn-wheel.yaml
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/777)
The `update-ttnn-wheel` workflow was broken since adding support for 20.04 and 22.04.
It looks like a previous update removed the `latest_version_short` tag. This PR adds it back in to get the correct latest TT-NN Wheel.
closes #777
> Fixes the workflow that picks up the latest TT-NN wheel

- .github/actions/common_repo_setup/action.yaml
- .github/actions/common_repo_setup/dependencies.json
- tests/models/bloom/test_bloom.py
- tests/models/detr/test_detr.py
- tests/models/mnist/test_mnist.py
- tests/models/torchvision/test_torchvision_object_detection.py
- tests/utils.py
Some models were marked `compilation_xfail`:
* Bloom
* MNIST
* TorchVision Object Detection
* DETR
This also adds configuration for Ubuntu 24.04 and configures the url for pip install in GH actions
Link to Github Issue
`Tests` has been broken for the past ~3 weeks, preventing auto-merging.
As a short-term fix, failing models were marked `compilation_xfail`. The `common_repo_setup` action was also updated to successfully install PyTorch cpu-only packages.
> Changelist to get `Tests` passing on main

- requirements.txt
> Update TT-NN to 0.56.0-rc47

- tests/models/dino/test_dino.py
This is just an embedding model, so there is no attempt to make the model results human-readable.
N/A
Learning workflow of adding models
Adds the DINOv2 model for testing based on the example at https://huggingface.co/facebook/dinov2-base
> Adds DINOv2 model to model tests

- tests/models/mobilenet_ssd/test_mobilenet_ssd.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
This has been fixed in tt-metal, so we can now use tensor expand on the last dimension. This also allows us to run mobilenet_ssd end to end.
closes 436
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/436)
Previously, we could not call ttnn.repeat to expand on the last dimension, but now we can.
Removed the check for expanding the last dimension. Marked MobileNet_ssd as end to end.
> Updates conversion of torch.expand to ttnn.repeat to allow repeating on last dimension.

- torch_ttnn/backend.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/target_wrappers.py
I tried to separate changes into atomic commits. That is, each commit contains a (mostly) related set of changes, and I would expect tests to pass after any given commit.
There were a handful of functions that I was able to cut down significantly, but I would like to remove more of the special cases in the future.
I have been looking at most of this code long enough that I am losing a sense of what is unreadable, so hoping to get some other opinions.
I also considered making some bigger changes, but am not sure if it is worthwhile. Please let me know your thoughts in comments:
1. Changing variable name `spec` to something more descriptive like `desired_alignment`
2. Changing control flow. Right now each of the transitions (Torch->Ttnn, Ttnn->Torch, and Ttnn->Ttnn) flow through the same …
> Refactor AddDataMovePass

- .github/workflows/before_merge.yaml
Not available
`Collect Metrics Report` step of the `collect-metrics` jobs fails due to not using the correct method to get run id. This happens when the before_merge workflow is triggered with anything other than `None`
Uses the correct syntax to get run id
> Fix workflow id in github workflows

- requirements.txt
Newer version breaks the runners. Will change back once runners are updated
> Reverted tt-metal version to when the support python3.8

- tests/lowering/creation/test_clone.py
- torch_ttnn/passes/lowering/to_tt_pass.py
`aten.clone` is used often to make sure the tensor is not a view of another tensor which can cause problems for some ops. Pytorch inserts this whenever it needs to. However, when we're dealing with TTNN tensors, we don't need to worry about this, so there's usually no need to convert to `ttnn.clone`. 
Unless `aten.clone` has an input from the graph arguments and is also returned as an output, we will remove the op entirely.
For example, `aten.clone` will not be removed and converted to `ttnn.clone` in this instance only. This is for unit testing purposes.
```
def forward(arg0):
clone = aten.clone(arg0)
return clone
```
> Optimize out conversion from `aten.clone`

- requirements.txt
- tests/autogen_op/ALL/test_ALL_aten_squeeze_dim.py
- tests/lowering/creation/test_full.py
- tests/lowering/creation/test_full_like.py
- tests/lowering/tensor_manipulation/test_squeeze.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- torch_ttnn/utils.py
Github Issues:
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/588 
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/110 
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/635
https://github.com/tenstorrent/tt-metal/issues/19746
https://github.com/tenstorrent/tt-metal/issues/16263
aten.squeeze.default, aten.full, aten.fill.Scalar, aten.memory_format used to fallback fully, or partially because of limited 0-rank tensor support in ttnn. aten.squeeze.default was not supported by ttnn till recently. 
Removed fallback for those operations. 
Updated tests to cover 0-rank shapes
> Remove fallback for aten.squeeze.default, aten.full, aten.fill.Scalar, aten.memory_format

- tests/models/dino/test_dino.py
- tests/tools/test_nested_output_accuracy.py
- tests/utils.py
Issue was discovered because of inconsistent accuracy values between the pytest run and generated accuracy script https://github.com/tenstorrent/pytorch2.0_ttnn/issues/835
Some outputs are nested Dict types. For example, CLIP has an output that has the following keys:
```
CLIPOutput = {
"logits_per_image",
"logits_per_text",
"text_embeds",
"image_embeds",
"text_model_output" : {
"last_hidden_state",
"pooler_output"
},
"vision_model_output" : {
"last_hidden_state",
"pooler_output"
}
}
```
Currently, `calculate_accuracy` silently skips the nested outputs so only the first 4 items are factored into the calculation. 
- Recursively walk through each item including nested Dicts and Lists until torch tensors are found and calculate the mean of the accumulated pcc values.
- Include a unit test to …
> Handle nested outputs when calculating accuracy

- .github/workflows/run-tests.yaml
- torch_ttnn/passes/lowering/to_tt_pass.py
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/15132)
`ttnn.tanh` in it's current implementation causes low accuracy in at least 5 models (4 being e2e). Setting accuracy argument to True in `ttnn.tanh`, which internally sets it's implementation to a sequence of ttnn ops on tt-metal side, resolves this issue. 
Added line in to_tt_pass.py which sets kwargs if target node is `ttnn.tanh`.
> Set accuracy to True in `ttnn.tanh`

- .github/workflows/run-tests.yaml
- requirements.txt
- tests/lowering/eltwise/unary/test_tanh.py
- tests/lowering/tensor_manipulation/test_squeeze.py
- tests/models/bloom/test_bloom.py
- torch_ttnn/passes/lowering/target_wrappers.py
- torch_ttnn/passes/lowering/to_tt_pass.py
Revert recent changes that depend on RC63. In particular, the following
commits were reverted:
1d1b23a5e4ab3534aae0680bb6052c592ba2358d
0683def63d7670f98d1452f0f957de6eba74332d
part of afac9cfc81a925140199559ef2b15029c1f33cfa
> Temporarily revert changes that rely on nonexistent tt-metal version

- tests/lowering/eltwise/binary/test_add.py
- tests/lowering/eltwise/binary/test_div.py
- tests/lowering/eltwise/binary/test_mul.py
- tests/lowering/eltwise/binary/test_sub.py
- tests/lowering/eltwise/ternary/test_where.py
- torch_ttnn/passes/lowering/to_tt_pass.py
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/442)
There are several places in ToTtPass where we guard against scalar inputs for functions that now have support from the tt-metal side. By removing these guards and updating tests, we can convert more calls to ttnn calls.
This PR has separates commits for each part of the ToTtPass that has been updated. Each commit also updates relevant tests to exercise the new behavior.
Note that this change leaves one reference to issue 422 in ToTtPass, but it is resolved by https://github.com/tenstorrent/pytorch2.0_ttnn/pull/968
> Support <2 rank in Tile layout

- tests/lowering/creation/test_to_copy.py
- tests/lowering/tensor_manipulation/test_view.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_pass.py
While working on performance tuning for BERT and multi-device BERT, we realized there are many (450+) calls to ttnn.reshape in the generated code. Nearly all of these are due to the lowering of `aten.view` and `aten._unsafe_view`. This PR lowers to ttnn.experimental.view when valid. The benefit is that ttnn.experimental.view is guaranteed to be zero copy, so it is easier to understand the performance implications just by reading generated code.
Updates ToTtPass to lower `aten.view` to `ttnn.experimental.view`
Updates tests
> Lower aten.view and aten._unsafe_view to ttnn.experimental.view when valid

- docs/DevelopWithMetalFromSources.md
- tests/lowering/misc/test_argmax.py
1. Remove xfail tag for argmax
https://github.com/tenstorrent/tt-metal/issues/19576
Argmax op failed for some inputs, this is resolved now. More details in the PR linked above.
1. Remove xfail tag for argmax
2. Update documentation to remove reference to lfs in tt-metal repo.
> Mark argmax test as working

- .github/workflows/update-ttnn-wheel.yaml
Change update-ttnn-wheel to use new pattern for tt-metal RC names
Remove line for python3.8 since it is no longer supported
Problem showed up in this run:
https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/14660010318/job/41142164195
It also showed up yesterday when trying to update to the newest RC, but I just manually changed dependencies. This should fix it going forward
> Synchronize update-ttnn-wheel workflow with new tt-metal naming

- tests/lowering/eltwise/unary/test_abs.py
- tests/lowering/eltwise/unary/test_acos.py
- tests/lowering/eltwise/unary/test_acosh.py
- tests/lowering/eltwise/unary/test_asin.py
- tests/lowering/eltwise/unary/test_asinh.py
- tests/lowering/eltwise/unary/test_atan.py
- tests/lowering/eltwise/unary/test_atanh.py
- tests/lowering/eltwise/unary/test_clamp.py
- tests/lowering/eltwise/unary/test_cos.py
- tests/lowering/eltwise/unary/test_cosh.py
- tests/lowering/eltwise/unary/test_elu.py
- tests/lowering/eltwise/unary/test_expm1.py
- tests/lowering/eltwise/unary/test_isinf.py
- tests/lowering/eltwise/unary/test_isnan.py
- tests/lowering/eltwise/unary/test_log.py
- tests/lowering/eltwise/unary/test_log10.py
- tests/lowering/eltwise/unary/test_log1p.py
- tests/lowering/eltwise/unary/test_log2.py
- tests/lowering/eltwise/unary/test_logical_not.py
- tests/lowering/eltwise/unary/test_reciprocal.py
- tests/lowering/eltwise/unary/test_relu.py
- tests/lowering/eltwise/unary/test_sigmoid.py
- tests/lowering/eltwise/unary/test_sign.py
- tests/lowering/eltwise/unary/test_silu.py
- tests/lowering/eltwise/unary/test_sin.py
- tests/lowering/eltwise/unary/test_sinh.py
- tests/lowering/eltwise/unary/test_tan.py
- tests/lowering/eltwise/unary/test_tanh.py
- torch_ttnn/passes/lowering/to_tt_pass.py
Removes unneeded reshape calls for eltwise unary function calls
Updates tests to exercise new behavior
I noticed that `gelu` had reshape calls before and after in BERT that are unnecessary. This PR removes the reshape calls for all eltwise unary ttnn ops.
I also cleaned up the handling of `accuracy=True` for tanh to not squash any other kwargs passed in
> Reduce unnecessary reshape calls in generated code

- tests/lowering/misc/test_scaled_dot_product_attention.py
- torch_ttnn/backend.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/lowering/to_tt_guard_autogen.py
- torch_ttnn/passes/lowering/to_tt_pass.py
- torch_ttnn/utils.py
- Resolves #541
Convert `aten._scaled_dot_product_flash_attention` to a series of ops.  Future goal might be implementing it as a composite kernel op instead.
The source op is functionally equivalent to its high-level counterpart:
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html
- Remove fallback for torch.ops.aten._scaled_dot_product_flash_attention.default. 
- since ttnn.transformer.scaled_dot_product_attention requires last dimension padded to tile_size, I added padding nodes before and slicing after if needed. 
- Remove getitem(out, 0) node after ttnn.transformer.scaled_dot_product_attention and fix metadata, since it returns only 1 value (unlike torch self attention)
- add unittest for sdpa
- Add get_add_custom_object_in_graph and …
> Try lowering `aten._scaled_dot_product_flash_attention`

- .github/actions/common_cleanup/action.yaml
- .github/workflows/run-accuracy-tests.yaml
- .github/workflows/run-tests.yaml
- torch_ttnn/passes/analysis/multi_device_shard_analysis_pass.py
- torch_ttnn/passes/multi_device_pass.py
The upcoming release candidate changes mesh devices so `isinstance(mesh_device, ttnn.Device)` evaluates to true. This breaks some of our checks for when to run mesh device passes. This commit removes that part of the conditional.
> Fix mesh device passes not running with new metal release

- .github/workflows/community-issue-tagging.yml
- .github/workflows/update-docker-container.yaml
- requirements.txt
Previously, the docker update workflow would update regardless of whether tests pass. This PR fixes that issue.
It also bundles in the dependency update since the new docker container should work with updated dependences.
> Fix docker update to only update when tests pass

- torch_ttnn/passes/lowering/add_data_move_pass.py
There was a recent metal change that fixed tilizing on device. This PR removes special cases that are no longer required and always tilizes on device, which should be faster based on Pavlo's analysis.
Passed tests:
https://github.com/tenstorrent/pytorch2.0_ttnn/actions/runs/14938910366
> Change AddDataMovePass to always tilize on device

- torch_ttnn/passes/fusion_pass.py
- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/patterns/attention_pattern.py
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/992)
There are some operations in the compiled code that can be unified in a higher level call.
Bert attention should work with concatenated heads and reduce the amount of low level operations
Added a new compilation pass that unifies bert attention layers with higher level operations.
Before PR:
Runtime Iteration without cache: 9.11285948753357
Runtime Iteration with cache: 0.38252902030944824
After PR:
Runtime Iteration without cache: 8.339576005935669
Runtime Iteration with cache: 0.37560153007507324
Generated code here:
https://github.com/dgomezTT/BertCompiledOptimization/commit/1b31451af6c13ffaf66816bea95524afe67baad3
Before:
Runtime Iteration 0: 7.632845163345337
Runtime Iteration 1: 0.3204987049102783 …
> Fuse operations in Bert attention

- torch_ttnn/passes/lowering/to_tt_pass.py
Updated step validations, now different than 1 is a valid scenario. Since the compiler already fills with 1 when the array is empty, we can assume that will be always equals or bigger than 1
[Link to Github Issue](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/876)
Metal updated it's code, allowing slices bigger than 1
Updated the compiler code to be compatible with this new validation
> Updated slices validations in the compiler

- tests/conftest.py
None
`print_tabular` prints out the graph in a table format. However, the information can be noisy and redundant. We are already printing out the graph in Python-code format in backend.py. 
Remove this printout.
> Remove `print_tabular` from conftest

- .github/workflows/before_merge.yaml
- .github/workflows/run-tests.yaml
- .github/workflows/update-readme.yaml
- .github/workflows/update-ttnn-wheel.yaml
- tests/lowering/eltwise/binary/test_pow_scalar.py
- tests/lowering/eltwise/unary/test_tanh.py
There are a couple of small changes bundled together in this PR:
* Fix tanh and pow_scalar tests by manually seeding torch.rand
* These have been flaky, which causes unnecessary retriggering of before merge
* Fix bug in Update Documentation flow that prevented actually merging doc updates
* Fix how inputs are passed to Run Tests from Before Merge
* This bug caused all model tests to be run for 5 iterations, which slows down Before Merge significantly
> Fix flaky lowering tests and speed up CI

- .github/actions/common_model_tests/action.yaml
- .github/workflows/update-docker-container.yaml
- dockerfile/Dockerfile
- requirements.txt
Recently, dependency updates have been failing because metal now uses a custom MPI branch. To fix this, and other related issues going forward, we can change the base CI docker image to be the `dev` version from metal.
Additionally, this PR:
* Fixes the num_iterations input for run-tests to speed up CI merge runs
* Adds the right permissions for run-tests inside the update-docker-container workflow
* Updates dependencies to the latest RC
> Update docker base container

- torch_ttnn/passes/analysis/graph_module_analysis_pass.py
This fixes an error which was thrown while compiling this Gaussian splatting implementation:
[torch-splatting](https://github.com/hbb1/torch-splatting)
The error was: 
`Traceback (most recent call last):
File "/home/user/tt-metal/pytorch2.0_ttnn/torch_ttnn/passes/analysis/graph_module_analysis_pass.py", line 49, in <listcomp>
placeholder_args = [arg for arg in node.args[0] if arg.op == "placeholder"]
AttributeError: 'NoneType' object has no attribute 'op'`
Accounted for the fact that node args can be None for certain conditional execution paths in the graph.  This is done by adding `NoneType` checking to the node arguments before accessing their attributes.  This eliminates the error, and doesn't affect the function or logic of the code in any other way.
> AttributeError fix for graph analysis pass

- torch_ttnn/passes/lowering/add_data_move_pass.py
- torch_ttnn/passes/patterns/attention_pattern.py
- torch_ttnn/passes/patterns/soft_max_pattern.py
This fixes the issue where calling deallocate didn't actually deallocate the softmax tensor since we were previously using the in-place operation
The previous bug caused an issue for L1 memory configs since memory wasn't actually deallocated when tensor.deallocate() was called. This PR changes the op so memory will be deallocated
> Do not use in-place attention softmax operation

- .github/actions/common_cleanup/action.yaml
- .github/actions/common_repo_setup/action.yaml
- .github/workflows/run-accuracy-tests.yaml
- .github/workflows/run-tests.yaml
- .github/workflows/update-docker-container.yaml
- dockerfile/Dockerfile
- torch_ttnn/passes/analysis/multi_device_shard_analysis_pass.py
Recently, we have had issues with several GHA runners being flaky. In particular, the N300 runners have been down, which has blocked merges.
This PR adds support for running the multi-device tests in CIv2 infrastructure. It is also the first step to adding CIv2 support to all of our actions.
The main changes include modifying how the multi-device tests use pip and fixing a recursion bug in today's implementation of the multi-device shard analysis pass.
> Migrate multi device tests to CIv2

- requirements.txt
> Update TT-NN to 0.60.0rc18.dev6

- .github/workflows/update-ttnn-wheel.yaml
It was recently requested that we start using a different PyPI registry for our dev dependencies. This will allow the tt-metal team to no longer publish RC's on their releases page, which will aid DevEx.
This PR accomplishes this ask. Namely it:
- Fetches the latest nightly release from the new URL
- Updates requirements.txt with the new URL
- Updates submodules to the corresponding git hash for the cpp extension
This PR does not address the additional requirements to clean up our release flow (publishing releases to PyPI that align with the tt-metal releases, using pyproject.toml instead for dependencies)
closes #1119
> Use new nightly TT-NN wheels in dev dependencies

- requirements.txt
> Update TT-NN to 0.61.0rc1.dev2
